function[out]=jlab_settings(str)
%JLAB_SETTINGS  Specifies settings for customizable JLAB properties.
%
%   JLAB_SETTINGS specifies customizable properties, including: 
%  
%       linesytle types, for use with LINESTYLES
%       custom color schemes, for use with LINESTYLES
%       directory names, for use with e.g. MATSAVE.
%    
%   Do not edit this file directly.  Instead, following the same format
%   as in this function, create an m-file script (not a function)
%   called USERSETTINGS.  If you edit this file, your custom settings
%   will be lost if you upgrade JLAB in the future.
%   __________________________________________________________________
%   This is part of JLAB --- type 'help jlab' for more information
%   (C) 2006 J.M. Lilly --- type 'help jlab_license' for details
 
if nargin ==1
    if strcmp(str, '--t')
       jlab_settings_test,return
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%DIRNAMES
%
%  User-specified direcory locations

dirnames.matfiles='/Users/lilly/Desktop/Home/Matlab/matfiles';
dirnames.figures='/Users/lilly/Desktop/Home/Matlab/scratch';
dirnames.devel='/Users/lilly/Desktop/Home/Matlab/devel';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%LINESTYLES
%
%  User-specified line style sets for use with LINESTYLE.
%
%    linestyles.name={'COLOR','STYLE','WIDTH'};
%
%  Line handles will be cycled through the available styles,
%  colors, and widths, so that S, C, and W need not have the 
%  same length as the number of line handles nor as each other.
%
%  An ellipsis may be used (for C only) to indicate a repeated
%  last color, thus 'kbgr...' is equivalent to 'krbrrrrrrr...'.
linestyles.default={'bgrcmyk','-',1};
linestyles.black={'k','-',1};
linestyles.just1={'bDDDDDD...','-',[2 1 1 1 1 1 1]};
linestyles.just2={'bgDDDDD...','-',[2 2 1 1 1 1 1]};
linestyles.just3={'bgrDDDD...','-',[2 2 2 1 1 1 1]};
linestyles.just4={'bgrcDDD...','-',[2 2 2 2 1 1 1]};
linestyles.just5={'bgrcmDD...','-',[2 2 2 2 2 1 1]};
linestyles.just6={'bgrcmyD...','-',[2 2 2 2 2 2 1]};
linestyles.groups4={'kkkkbbbbggggrrrr','-',1};
linestyles.groups5={'kkkkkbbbbbgggggrrrrr','-',1};
linestyles.groups6={'kkkkkkbbbbbbggggggrrrrrr','-',1};
linestyles.groups7={'kkkkkkkbbbbbbbgggggggrrrrrrr','-',1};
linestyles.groups8={'kkkkkkkkbbbbbbbbggggggggrrrrrrrr','-',1};
linestyles.groups9={'kkkkkkkkkbbbbbbbbbgggggggggrrrrrrrrr','-',1};
linestyles.groups10={'kkkkkkkkkkbbbbbbbbbbggggggggggrrrrrrrrrr','-',1};
linestyles.thick={'bgrcmyk','-',2};
linestyles.two={'Ek',['- ';'--'],[2 1]};
linestyles.three={'kEk',['--';'- ';'- '],[2 2 1]};
linestyles.four={'EkEk',['--';'--';'- ';'- '],[2 1 2 1]};
linestyles.just2bw={'kkkkkkk...','-',[2.5 2.5 1 1 1 1 1]};
linestyles.triplets={'bbbgggrrr',['- ';'--';'- '],[1 2 2]};
linestyles.redgreenblue={'rgb',['-';'-';'-'],[1 1 1]};
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%COLORS
%
%  User-specified additional colors for use with LINESTYLE.
colors.k=[0 0 0];
colors.w=[1 1 1];
colors.b=[0 0 1];
colors.g=[0 0.5 0];
colors.r=[1 0 0];
colors.c=[0 0.75 0.75];
colors.m=[0.75 0 0.75];
colors.y=[0.75 0.75 0];
colors.A=(1-0)*[1 1 1];
colors.B=(1-1/10)*[1 1 1];
colors.C=(1-2/10)*[1 1 1];
colors.D=(1-3/10)*[1 1 1];
colors.E=(1-4/10)*[1 1 1];
colors.F=(1-5/10)*[1 1 1];
colors.G=(1-6/10)*[1 1 1];
colors.H=(1-7/10)*[1 1 1];
colors.I=(1-8/10)*[1 1 1];
colors.J=(1-9/10)*[1 1 1];
colors.K=(1-10/10)*[1 1 1];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

figsave.png='-dpng';
figsave.eps='-deps';
figsave.ps='-dps';
figsave.epsc='-depsc';
figsave.psc='-dpsc';

figsave.orient.landscape='orient landscape';

if exist('usersettings')==2
    usersettings;
end

try 
    eval(['out=' str ';'])
catch
    out=[];
end

function[]=jlabsettings_test
 
%reporttest('JSETTINGS',aresame())
